# --- App ---
spring.application.name=moduche

# --- DataSource (Supabase Pooler) ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=moduche&options=-c%20search_path=moduche,public
spring.datasource.username=postgres.kawzzzvmvjaftwkqtuqu
spring.datasource.password=nyotz3xVjOpPWvLI
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/moduche
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

# --- HikariCP (setting) ---
spring.datasource.hikari.pool-name=HikariPool-Moduche
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1


# --- JPA/Hibernate ---
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.properties.hibernate.default_schema=moduche


logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.orm.mapping=debug
logging.level.org.hibernate.metamodel.model.domain=debug


# AWS Credentials
spring.config.import=optional:file:.env[.properties]
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.s3.bucket=${AWS_BUCKET}

# --- SMTP ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kindokyeong@gmail.com
spring.mail.password=llzl fxht adwj yehx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# --- CSV read ---
csv.upload.dir=data