spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=moduche&options=-c%20search_path=moduche,public/moduche_dev
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      lettuce:
#        pool:
#          max-active: 20
#          max-idle: 10
#          min-idle: 1
  data:
    redis:
      host: 0.0.0.0
      port: 0000
      lettuce:
        pool:
          enabled: false

  config:
    import: optional:file:.env[.properties]

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}